apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IonosCloudCluster
metadata:
  labels:
    app.kubernetes.io/name: ionoscloudcluster
    app.kubernetes.io/instance: ionoscloudcluster-sample
    app.kubernetes.io/part-of: cluster-api-provider-ionoscloud
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-provider-ionoscloud
  name: ionoscloudcluster-sample
spec:
  # TODO(user): Add fields here
